/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as UsersUsersRouteImport } from './routes/Users/Users'
import { Route as SystemTicketsRouteImport } from './routes/System/Tickets'
import { Route as SystemCreateRouteImport } from './routes/System/Create'
import { Route as SystemCategoryRouteImport } from './routes/System/Category'
import { Route as SystemBookRouteImport } from './routes/System/Book'
import { Route as SystemAutherRouteImport } from './routes/System/Auther'
import { Route as NewsNewsRouteImport } from './routes/News/News'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const UsersUsersRoute = UsersUsersRouteImport.update({
  id: '/Users/Users',
  path: '/Users/Users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemTicketsRoute = SystemTicketsRouteImport.update({
  id: '/System/Tickets',
  path: '/System/Tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCreateRoute = SystemCreateRouteImport.update({
  id: '/System/Create',
  path: '/System/Create',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCategoryRoute = SystemCategoryRouteImport.update({
  id: '/System/Category',
  path: '/System/Category',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemBookRoute = SystemBookRouteImport.update({
  id: '/System/Book',
  path: '/System/Book',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAutherRoute = SystemAutherRouteImport.update({
  id: '/System/Auther',
  path: '/System/Auther',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsRoute = NewsNewsRouteImport.update({
  id: '/News/News',
  path: '/News/News',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/News/News': typeof NewsNewsRoute
  '/System/Auther': typeof SystemAutherRoute
  '/System/Book': typeof SystemBookRoute
  '/System/Category': typeof SystemCategoryRoute
  '/System/Create': typeof SystemCreateRoute
  '/System/Tickets': typeof SystemTicketsRoute
  '/Users/Users': typeof UsersUsersRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/News/News': typeof NewsNewsRoute
  '/System/Auther': typeof SystemAutherRoute
  '/System/Book': typeof SystemBookRoute
  '/System/Category': typeof SystemCategoryRoute
  '/System/Create': typeof SystemCreateRoute
  '/System/Tickets': typeof SystemTicketsRoute
  '/Users/Users': typeof UsersUsersRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/News/News': typeof NewsNewsRoute
  '/System/Auther': typeof SystemAutherRoute
  '/System/Book': typeof SystemBookRoute
  '/System/Category': typeof SystemCategoryRoute
  '/System/Create': typeof SystemCreateRoute
  '/System/Tickets': typeof SystemTicketsRoute
  '/Users/Users': typeof UsersUsersRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/News/News'
    | '/System/Auther'
    | '/System/Book'
    | '/System/Category'
    | '/System/Create'
    | '/System/Tickets'
    | '/Users/Users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/News/News'
    | '/System/Auther'
    | '/System/Book'
    | '/System/Category'
    | '/System/Create'
    | '/System/Tickets'
    | '/Users/Users'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/about'
    | '/login'
    | '/News/News'
    | '/System/Auther'
    | '/System/Book'
    | '/System/Category'
    | '/System/Create'
    | '/System/Tickets'
    | '/Users/Users'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  NewsNewsRoute: typeof NewsNewsRoute
  SystemAutherRoute: typeof SystemAutherRoute
  SystemBookRoute: typeof SystemBookRoute
  SystemCategoryRoute: typeof SystemCategoryRoute
  SystemCreateRoute: typeof SystemCreateRoute
  SystemTicketsRoute: typeof SystemTicketsRoute
  UsersUsersRoute: typeof UsersUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/Users/Users': {
      id: '/Users/Users'
      path: '/Users/Users'
      fullPath: '/Users/Users'
      preLoaderRoute: typeof UsersUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/System/Tickets': {
      id: '/System/Tickets'
      path: '/System/Tickets'
      fullPath: '/System/Tickets'
      preLoaderRoute: typeof SystemTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/System/Create': {
      id: '/System/Create'
      path: '/System/Create'
      fullPath: '/System/Create'
      preLoaderRoute: typeof SystemCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/System/Category': {
      id: '/System/Category'
      path: '/System/Category'
      fullPath: '/System/Category'
      preLoaderRoute: typeof SystemCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/System/Book': {
      id: '/System/Book'
      path: '/System/Book'
      fullPath: '/System/Book'
      preLoaderRoute: typeof SystemBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/System/Auther': {
      id: '/System/Auther'
      path: '/System/Auther'
      fullPath: '/System/Auther'
      preLoaderRoute: typeof SystemAutherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/News/News': {
      id: '/News/News'
      path: '/News/News'
      fullPath: '/News/News'
      preLoaderRoute: typeof NewsNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  NewsNewsRoute: NewsNewsRoute,
  SystemAutherRoute: SystemAutherRoute,
  SystemBookRoute: SystemBookRoute,
  SystemCategoryRoute: SystemCategoryRoute,
  SystemCreateRoute: SystemCreateRoute,
  SystemTicketsRoute: SystemTicketsRoute,
  UsersUsersRoute: UsersUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
