/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAboutRouteImport } from './routes/_auth/about'
import { Route as AuthUsersUsersRouteImport } from './routes/_auth/Users/Users'
import { Route as AuthSystemTicketsRouteImport } from './routes/_auth/System/Tickets'
import { Route as AuthSystemCreateRouteImport } from './routes/_auth/System/Create'
import { Route as AuthSystemCategoryRouteImport } from './routes/_auth/System/Category'
import { Route as AuthSystemBookRouteImport } from './routes/_auth/System/Book'
import { Route as AuthSystemAutherRouteImport } from './routes/_auth/System/Auther'
import { Route as AuthNewsNewsRouteImport } from './routes/_auth/News/News'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAboutRoute = AuthAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersUsersRoute = AuthUsersUsersRouteImport.update({
  id: '/Users/Users',
  path: '/Users/Users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemTicketsRoute = AuthSystemTicketsRouteImport.update({
  id: '/System/Tickets',
  path: '/System/Tickets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemCreateRoute = AuthSystemCreateRouteImport.update({
  id: '/System/Create',
  path: '/System/Create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemCategoryRoute = AuthSystemCategoryRouteImport.update({
  id: '/System/Category',
  path: '/System/Category',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemBookRoute = AuthSystemBookRouteImport.update({
  id: '/System/Book',
  path: '/System/Book',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemAutherRoute = AuthSystemAutherRouteImport.update({
  id: '/System/Auther',
  path: '/System/Auther',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsNewsRoute = AuthNewsNewsRouteImport.update({
  id: '/News/News',
  path: '/News/News',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthAboutRoute
  '/News/News': typeof AuthNewsNewsRoute
  '/System/Auther': typeof AuthSystemAutherRoute
  '/System/Book': typeof AuthSystemBookRoute
  '/System/Category': typeof AuthSystemCategoryRoute
  '/System/Create': typeof AuthSystemCreateRoute
  '/System/Tickets': typeof AuthSystemTicketsRoute
  '/Users/Users': typeof AuthUsersUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AuthAboutRoute
  '/': typeof AuthIndexRoute
  '/News/News': typeof AuthNewsNewsRoute
  '/System/Auther': typeof AuthSystemAutherRoute
  '/System/Book': typeof AuthSystemBookRoute
  '/System/Category': typeof AuthSystemCategoryRoute
  '/System/Create': typeof AuthSystemCreateRoute
  '/System/Tickets': typeof AuthSystemTicketsRoute
  '/Users/Users': typeof AuthUsersUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/about': typeof AuthAboutRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/News/News': typeof AuthNewsNewsRoute
  '/_auth/System/Auther': typeof AuthSystemAutherRoute
  '/_auth/System/Book': typeof AuthSystemBookRoute
  '/_auth/System/Category': typeof AuthSystemCategoryRoute
  '/_auth/System/Create': typeof AuthSystemCreateRoute
  '/_auth/System/Tickets': typeof AuthSystemTicketsRoute
  '/_auth/Users/Users': typeof AuthUsersUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/News/News'
    | '/System/Auther'
    | '/System/Book'
    | '/System/Category'
    | '/System/Create'
    | '/System/Tickets'
    | '/Users/Users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/'
    | '/News/News'
    | '/System/Auther'
    | '/System/Book'
    | '/System/Category'
    | '/System/Create'
    | '/System/Tickets'
    | '/Users/Users'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/about'
    | '/_auth/'
    | '/_auth/News/News'
    | '/_auth/System/Auther'
    | '/_auth/System/Book'
    | '/_auth/System/Category'
    | '/_auth/System/Create'
    | '/_auth/System/Tickets'
    | '/_auth/Users/Users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/about': {
      id: '/_auth/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthAboutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/Users/Users': {
      id: '/_auth/Users/Users'
      path: '/Users/Users'
      fullPath: '/Users/Users'
      preLoaderRoute: typeof AuthUsersUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/System/Tickets': {
      id: '/_auth/System/Tickets'
      path: '/System/Tickets'
      fullPath: '/System/Tickets'
      preLoaderRoute: typeof AuthSystemTicketsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/System/Create': {
      id: '/_auth/System/Create'
      path: '/System/Create'
      fullPath: '/System/Create'
      preLoaderRoute: typeof AuthSystemCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/System/Category': {
      id: '/_auth/System/Category'
      path: '/System/Category'
      fullPath: '/System/Category'
      preLoaderRoute: typeof AuthSystemCategoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/System/Book': {
      id: '/_auth/System/Book'
      path: '/System/Book'
      fullPath: '/System/Book'
      preLoaderRoute: typeof AuthSystemBookRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/System/Auther': {
      id: '/_auth/System/Auther'
      path: '/System/Auther'
      fullPath: '/System/Auther'
      preLoaderRoute: typeof AuthSystemAutherRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/News/News': {
      id: '/_auth/News/News'
      path: '/News/News'
      fullPath: '/News/News'
      preLoaderRoute: typeof AuthNewsNewsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAboutRoute: typeof AuthAboutRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthNewsNewsRoute: typeof AuthNewsNewsRoute
  AuthSystemAutherRoute: typeof AuthSystemAutherRoute
  AuthSystemBookRoute: typeof AuthSystemBookRoute
  AuthSystemCategoryRoute: typeof AuthSystemCategoryRoute
  AuthSystemCreateRoute: typeof AuthSystemCreateRoute
  AuthSystemTicketsRoute: typeof AuthSystemTicketsRoute
  AuthUsersUsersRoute: typeof AuthUsersUsersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAboutRoute: AuthAboutRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthNewsNewsRoute: AuthNewsNewsRoute,
  AuthSystemAutherRoute: AuthSystemAutherRoute,
  AuthSystemBookRoute: AuthSystemBookRoute,
  AuthSystemCategoryRoute: AuthSystemCategoryRoute,
  AuthSystemCreateRoute: AuthSystemCreateRoute,
  AuthSystemTicketsRoute: AuthSystemTicketsRoute,
  AuthUsersUsersRoute: AuthUsersUsersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
